name: news_app
description: "News application with clean architecture."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  #icon
  ionicons: ^0.2.2

  # state management
  flutter_bloc: ^8.1.6

  # comapring dart objects
  equatable: ^2.0.5

  # service locator
  get_it: ^7.7.0

  # date formatting
  intl: ^0.19.0

  # database
  floor: ^1.5.0

  # make http requests
  retrofit: ^4.2.0

  # hooks
  flutter_hooks: ^0.20.5

  # cached image
  cached_network_image: ^3.4.1

  # dio client
  dio: ^5.6.0

  # dotenv
  flutter_dotenv: ^5.1.0

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

  retrofit_generator: ^8.2.0
  floor_generator: ^1.4.2
  build_runner: ^2.1.2

flutter:
  uses-material-design: true

  assets:
    - .env

  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/muli/Muli.ttf
        - asset: assets/fonts/muli/Muli-Bold.ttf
          weight: 700
        - asset: assets/fonts/muli/Muli-Light.ttf
          weight: 300
